### ISSUE TITLE
epic: automation and integration of the new systest framework

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/pm#116]
### Infra
- [x] https://github.com/spacemeshos/pm/issues/114
- [x] https://github.com/spacemeshos/pm/issues/115

### Tests
- [ ] https://github.com/spacemeshos/pm/issues/113
- [ ] https://github.com/spacemeshos/pm/issues/112
