### ISSUE TITLE
Certification Round in the Hare Protocol

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#120]
https://www.notion.so/spacemesh/Certification-Round-in-the-Hare-Protocol-93ef75e600684887a561a342e044264c

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3284
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3283
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3199
