### ISSUE TITLE
Codec migration to scale

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#125]
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3271
- [x] https://github.com/spacemeshos/go-scale/issues/
- [x] https://github.com/spacemeshos/smapp/issues/960
- [x] https://github.com/spacemeshos/smapp/issues/959
- [x] https://github.com/spacemeshos/post/pull/61
