### ISSUE TITLE
Mesh data sync

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#127]
- [x] https://github.com/spacemeshos/SMIPS/issues/51 (90% implemented)
- [x] https://github.com/spacemeshos/go-spacemesh/pull/3294
- [x] https://github.com/spacemeshos/go-spacemesh/pull/3307
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2507

**Comment by pigmej** [comment]
Parts of https://github.com/spacemeshos/SMIPS/issues/60 will be post-genesis.
https://github.com/spacemeshos/SMIPS/issues/51 will be closed with https://github.com/spacemeshos/go-spacemesh/issues/2507
