### ISSUE TITLE
Production ready network deployment

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#132]
We shall use Infrastructure as a Code pattern to simplify our ops and also add robustness to the systems.

- [ ] https://github.com/spacemeshos/Infrastructure/issues/23
- [x] https://github.com/spacemeshos/Infrastructure/issues/24
- [x] https://github.com/spacemeshos/Infrastructure/issues/14
- [x] https://github.com/spacemeshos/Infrastructure/issues/11
- [x] https://github.com/spacemeshos/Infrastructure/issues/7
