### ISSUE TITLE
VM implementation for genesis

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#138]
We should have ready enough implementation of vm for our genesis.

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3267
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3339
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3272
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3270
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3269
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3268
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3392
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3391
