### ISSUE TITLE
Implement final address design

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#140]
Based on #106 
Tracked in:
- [x] https://github.com/spacemeshos/api/issues/172
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3315
- [x] https://github.com/spacemeshos/smapp/issues/936
