### ISSUE TITLE
Mutable ballots

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#183]
More info: https://github.com/spacemeshos/pm/issues/123

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3637
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3636
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3635
