### ISSUE TITLE
Improve testing of the networks

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#184]
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3703
- [ ] set realistic latency with some % of packet drops for the whole network (100-200ms for rt, .5% packet drop)
- [ ] use varying transaction load to see what difference it makes
- [ ] 5-10% of smeshers that are periodically disconnected for 1-10 layers duration
- [ ] 5-10% that are periodically turned off for 1-10 layers
- [ ] 5-10% that are consistently running with slow network or slightly inconsistent time (2-5s)
- [ ] disconnect nodes during sync for 10s-60s

We need to remember that  for all of the above use network with longer epochs, otherwise it is too easy to create epoch-wide partition
