### ISSUE TITLE
Tortoise Protocol genesis improvements

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#185]
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3646
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3644
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3643
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3642
