### ISSUE TITLE
Storage size decrement

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#191]
If someone's POS spans across multiple devices, it's getting more and more plausible that some devices will fail.

Therefore to still be able to operate successfully, we need to have the possibility of "storage size decrement."

The exact details are still TBD, and it needs to be further discussed by @noamnelke and @countvonzero 

UPDATE:
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3773 ATX: allow variable units over time for the same smesher ID
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3816 ATX: handle different phase shifts from poet servers
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3775 mining: graceful exit

**Comment by noamnelke** [comment]
Added a rough spec here: https://github.com/spacemeshos/go-spacemesh/issues/3773#issuecomment-1339597893

**Comment by pigmej** [comment]
https://github.com/spacemeshos/pm/issues/253 closing in favor of this.
