### ISSUE TITLE
Wallet CLI tool

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#218]
- [x] make sure wallet format is compatible (with smapp, other standards) (https://github.com/spacemeshos/pm/issues/213, https://github.com/spacemeshos/SMIPS/issues/17)
- [x] CLI tool hardware wallet support (https://github.com/spacemeshos/smcli/issues/10)
- [ ] update spacemesh ledger app address format (https://github.com/spacemeshos/ledger-app/issues/5)
- [ ] update spacemesh ledger app tx format (can do this later) (https://github.com/spacemeshos/ledger-app/issues/6)
- [x] support for generating multiple derived keys (https://github.com/spacemeshos/smcli/issues/11)

**Comment by lrettig** [comment]
Main genesis-critical tasks are done here. Will handle the rest in #230 and linked issues.
