### ISSUE TITLE
Poet V2

### ISSUE THREAD

**Issue by poszu** [spacemeshos/pm#257]
Redesign poet to separate user-facing _Registration_ service and a _Worker_ service that is not reachable from the internet.
Tasks:
- [ ] https://github.com/spacemeshos/poet/issues/367
- [x] https://github.com/spacemeshos/poet/issues/355
- [ ] https://github.com/spacemeshos/poet/issues/365
- [ ] https://github.com/spacemeshos/Applications/issues/224
