### ISSUE TITLE
Improve sync/gossip

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#280]
Right now it's harder to sync than we'd like. Sync sometimes gets stuck in spite of a node having many peers (e.g., https://github.com/spacemeshos/go-spacemesh/issues/5127) and the only way to get it unstuck is to restart the node and thus refresh the peer set entirely. Sync is also slower than we'd like.

This is a meta-issue to track user-facing sync issues and pending improvements. Upcoming go-spacemesh release v1.2.2 should address many of these issues.

- [x] https://github.com/spacemeshos/go-spacemesh/issues/4603
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3459
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/4958
- [x] #275
- [ ] #272 

See also: https://github.com/search?q=org%3Aspacemeshos+label%3Aarea%2Fsync&type=issues
