### ISSUE TITLE
Modular node architecture

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#282]
Meta issue to track several workstreams related to making the current node architecture more modular. Much of this work involves updating go-spacemesh to manage multiple smesher identities.

- [x] #259 
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5088
- [x] https://github.com/spacemeshos/api/issues/269
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5042
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5131
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5149
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5086
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5089
- [x] https://github.com/spacemeshos/go-spacemesh/issues/5090

See also: https://github.com/spacemeshos/go-spacemesh/labels/feat%2Fmulti%20smeshers

**Comment by pigmej** [comment]
This got mostly done and then evolved into https://github.com/spacemeshos/pm/issues/334
