### ISSUE TITLE
Improve explorer/dashboard

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#284]
Meta issue to track user-facing improvements to the explorer and dashboard:

- [ ] https://github.com/spacemeshos/explorer-backend/issues/68 (requires https://github.com/spacemeshos/go-spacemesh/issues/4863, https://github.com/spacemeshos/go-spacemesh/issues/4529)
- [x] https://github.com/spacemeshos/explorer-frontend/issues/207
- [x] https://github.com/spacemeshos/explorer-backend/issues/78
- [x] https://github.com/spacemeshos/dash-backend/issues/14
