### ISSUE TITLE
Smesher UX improvements

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#328]
Currently we're lacking on the smesher experience.

## Proof generation improvements

- [ ] https://github.com/spacemeshos/post-rs/issues/81
- [ ] https://github.com/spacemeshos/post/issues/147
- [x] https://github.com/spacemeshos/post-rs/issues/343

## Proof status reporting

- [ ] Node should be able to better report the progress (or lack of it) for given post service and acessible via node api
    * proof progress
    * when is it expected to start proving etc.
- [ ] Serve timings and durations of each phase of the proof generation via API. We need to be careful here when we will have interruptible proof generation.

## Provide information about the state of the node

Add endpoints in the GRPC API to

- [x] spacemeshos/go-spacemesh#6149
   - from which epoch rewards are expected
   - why rewards are NOT expected in THIS epoch (failed to submit to poet in the previous round, failed to generate proof, failed to publish ATX etc)
   - what is the current state of the ID (ok, equivocated, etc)
   - when ATX was published
   - when did it register to next poet round etc.
- [x] spacemeshos/go-spacemesh#6174

## Node identity management

Most likely via some external CLI

- [ ] https://github.com/spacemeshos/go-spacemesh/issues/5563
- [ ] Grow / Shrink POST
    * https://github.com/spacemeshos/go-spacemesh/issues/5921
    * this is mostly done just lacks tooling

## General improvements / helpers

- [x] https://github.com/spacemeshos/go-spacemesh/issues/5565
- [x] https://github.com/spacemeshos/post-rs/issues/220
- [ ] https://github.com/spacemeshos/post/issues/269
- [ ] `NODE INITIALIZATION FAILED {"ERROR": "FAILED TO COMPUTE LABELS: INITIALIZING SCRYPTER: INVALID PROVIDER ID"}` when user moves from init to a "node" this should yield better info.
- [ ] Simple orchestrator that would run services sequentially one after another.
	* There are people who need that heavily, they claim that the DAG approach is too complex and they often result to hacky solutions.

## ATX Builder improvements
This category is slightly different and kinda touches Smesher UX but is also more like atx builder itself. Need to think about them yet.

- [x] https://github.com/spacemeshos/go-spacemesh/issues/6041
- [x] https://github.com/spacemeshos/go-spacemesh/issues/6035
