### ISSUE TITLE
Node Split PoC

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/pm#337]
This is the prerequisite for https://github.com/spacemeshos/pm/issues/334.

The expected outcome is that:

- [x] node split setup works on testnet
- [x] We have gathered reqs that are needed to write the final implementation
- [x] The expectation is that the setup will be *never* used on production as completed in the node-split PoC.
- [x] all unnecessary protocols and communication should be removed from the smeshing-service part.
- [x] a tech demo delivered to the community

**Comment by jellonek** [comment]
With https://github.com/spacemeshos/go-spacemesh/pull/6521 we have confirmed that such setup works on testnet.

Beside that changes included in https://github.com/spacemeshos/go-spacemesh/tree/node-split-poc already have stripped from client side most if not all unnecessary protocols (I'm still trying to confirm that).

**Comment by pigmej** [comment]
We're currently gathering the requirements for final implementation. The PoC was delivered https://github.com/spacemeshos/go-spacemesh/releases/tag/node-split-poc-1.0.0.

**Comment by pigmej** [comment]
Beta phase here https://github.com/spacemeshos/pm/issues/338
