### ISSUE TITLE
Hare improvements

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/pm#34]
### Phase 1 (must have)
- [ ] [Terminate old hare processes if max iterations reached](https://github.com/spacemeshos/go-spacemesh/issues/2303) (owner: @sidsankhe)
- [ ] [Support empty set hare result](https://github.com/spacemeshos/go-spacemesh/issues/1967) | [Differentiate between negative and explicitly neutral votes, while waiting for hare](https://github.com/spacemeshos/go-spacemesh/issues/2203) | [Hare behavior if preround fails](https://github.com/spacemeshos/go-spacemesh/issues/2311) (TODO: unify issues) (owner: @sudachen)
- [ ] [Add syntactic validity bit to block data structure - use in hare and tortoise voting](https://github.com/spacemeshos/go-spacemesh/issues/2304) (owner: @sudachen)
- [ ] [Increase hdist](https://github.com/spacemeshos/go-spacemesh/issues/2306) (owner: @sudachen)
- [ ] [Termination Round](https://github.com/spacemeshos/go-spacemesh/issues/1966) (owner: @sidsankhe)

### Phase 2 (good to have)

- [ ] Security concern: [preround status optimization](https://github.com/spacemeshos/go-spacemesh/issues/1965)
- [ ] [Scaling tasks](https://github.com/spacemeshos/go-spacemesh/issues/1968)
- [ ] Adversarial testing

---

[All backlog tasks](https://github.com/spacemeshos/go-spacemesh/labels/Hare%20Protocol)
