### ISSUE TITLE
Implement new 0.3 transaction format across the whole platform

### ISSUE THREAD

**Issue by avive** [spacemeshos/pm#65]
Blocker:  new TX format (with AA) final smipp fully describing the tx network encoding.

Tasks:
- [ ] `smapp` - create and display txs.
- [ ] `smrepl` - create and display txs.
- [ ] `js-ledger-sdk`
- [ ] `go-ledger-sdk`
- [ ] `ledger-app` - properly parse 0.3 txs for on-screen display. Properly sign. Support all 0.3 tx types.
- [ ] `explorer backend` - parse 0.3 txs and write data items in local db. 
- [ ] `explorer frontend` - properly display 0.3 transactions.
