### ISSUE TITLE
Transition to SVM

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/pm#89]
The transition to SVM will be performed in 3 major phases:

# Phase 1

- [x] Identify all components that should be replaced by SVM functionality.
- [x] Create issues on the SVM side to implement any missing functionality:
  - [x] https://github.com/spacemeshos/svm/issues/373
  - [x] https://github.com/spacemeshos/svm/issues/374
  - [x] https://github.com/spacemeshos/svm/issues/375
  - [x] https://github.com/spacemeshos/svm/issues/376
  - [x] https://github.com/spacemeshos/svm/issues/377
- [ ] https://github.com/spacemeshos/svm/issues/426

# Phase 2

- [x] https://github.com/spacemeshos/go-spacemesh/issues/2827
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2828
- [x] https://github.com/spacemeshos/go-spacemesh/issues/2829

The last two issues can be worked on in parallel, although minor conflicts are to be expected.

# Phase 3

## Prerequisites
<details>
<summary><a href="https://github.com/spacemeshos/go-svm"><code>go-svm</code></a> being fully implemented and exposing the following functions (click to expand)</summary>

- `validate_deploy(message) -> validation_error`
- `validate_spawn(message) -> validation_error`
- `validate_call(message) -> validation_error`
- `deploy(envelope, message, context) -> deploy_receipt`
- `spawn(envelope, message, context) -> spawn_receipt`
- `verify(envelope, message, context) -> call_receipt`
- `call(envelope, message, context) -> call_receipt`
- https://github.com/spacemeshos/svm/issues/373
- https://github.com/spacemeshos/svm/issues/374
- https://github.com/spacemeshos/svm/issues/375
- https://github.com/spacemeshos/svm/issues/376
- https://github.com/spacemeshos/svm/issues/377

</details>

<details>
<summary>SVM codec for encoding transactions implemented and ready (click to expand)</summary>

Should be exposed by `go-svm` as a utility, for `go-spacemesh` and `sm-repl` to use.

SVM codec instantiation boilerplate code: https://github.com/spacemeshos/go-svm-old/tree/master/codec

</details>

## Tasks

- [ ] Add `go-svm` to `go-spacemesh` as a dependency (mostly about getting the build/linkage to work).
- [ ] Encode transactions using SVM codec.
- [ ] Create an SVM package replacement with identical method signature and re-implement all methods using `go-svm` exposed methods.
- [ ] Ensure all unit tests and system tests pass.

**Comment by lrettig** [comment]
largely done, and what's remaining here will be obviated by new VM design.
