### ISSUE TITLE
Finalize research for 0.3

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/pm#92]
Roughly in order of priority and planned task sequence:

- [x] #100 is an enabler for transaction selection. There's an epic for it with dev tasks and a placeholder SMIP.
- [ ] #42: SMIP is complete. Transaction syntax requires this.
- [ ] #104 (generalized nonces, inside-the-VM): design is mostly complete but SMIP is still a placeholder.
- [x] #108
- [x] #106
- [ ] #13 (binary trie?)
- [ ] #43 Got research feedback. Depends on serialization question and nonce design. Need to rewrite SMIP to reflect final design.
- [ ] #14 (See also https://github.com/spacemeshos/SMIPS/issues/50): There is a draft SMIP, but it needs to be updated with the latest understanding of unified content blocks, and a few sections need to be filled in.
- [ ] conservative balance design
- [ ] #10 (See also https://github.com/spacemeshos/SMIPS/issues/37): There is a SMIP but it's incomplete and there are a number of outstanding questions related to: criteria for gossip propagation/mempool admittance and eviction, conservative balances, nonce design, transaction selection, etc.
  - [ ] mempool management: admittance and eviction criteria
- [ ] End-to-end recommended/default inside-the-VM transaction handling
  - nonce? deduplication, invalidation
  - verify
  - constructor
  - others?
- [ ] #5 (See also https://github.com/spacemeshos/SMIPS/issues/38): There is a SMIP but still a few open questions involving: layer vs. epoch smoothing, base fees/miner incentive fees, fee maturation, sorting transactions, transaction receipts.
- [ ] #3 (See also https://github.com/spacemeshos/SMIPS/issues/49): There is a complete SMIP but still a number of open questions involving: transaction format, signing, fixed gas mode, funding, SVM API, nonce design.
  - [ ] #105
- [ ] #8 (See also https://github.com/spacemeshos/SMIPS/issues/39): There is only a placeholder SMIP. A complete SMIP needs to be written.
- [ ] #93: Research has discussed better algorithms and data structures but has not yet delivered a final recommendation. Not 100% sure whether this is essential for genesis, but, given our nonce scheme, it would be very nice to have.
- [ ] #99: Just a placeholder issue, no SMIP. Not terribly complex, but there are still a few outstanding questions. Nice to have, not absolutely essential for genesis.
- [ ] Mesh data sync (https://github.com/spacemeshos/SMIPS/issues/51): mostly already implemented (@countvonzero)
- [ ] Mesh state sync (https://github.com/spacemeshos/SMIPS/issues/60): mostly done research-wise (@countvonzero)

**Comment by lrettig** [comment]
Closing in favor of https://github.com/orgs/spacemeshos/projects/22
